name: Build AzureSignTool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish EXE
        run: |
          dotnet publish src/AzureSignTool/AzureSignTool.csproj `
            --configuration Release `
            --runtime win-x64 `
            --self-contained true `
            --output publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzureSignTool-win-x64
          path: publish/
