name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      # Build 1: Self-contained single file (portable)
      - name: Publish self-contained single-file
        run: dotnet publish src/AzureSignTool/AzureSignTool.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishAot=false -o publish/self-contained

      # Build 2: Framework-dependent (small)
      - name: Publish framework-dependent
        run: dotnet publish src/AzureSignTool/AzureSignTool.csproj -c Release -r win-x64 --self-contained false -o publish/framework

      # Upload both EXEs to the GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: AzureSignTool ${{ github.ref_name }}
          files: |
            publish/self-contained/AzureSignTool.exe
            publish/framework/AzureSignTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
