name: Build and Release AzureSignTool

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with v

jobs:
  build:
    name: Build AzureSignTool
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build src/AzureSignTool/AzureSignTool.csproj -c Release

      - name: Publish self-contained EXE
        run: dotnet publish src/AzureSignTool/AzureSignTool.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishAot=false -o publish

      - name: Archive EXE
        uses: actions/upload-artifact@v4
        with:
          name: AzureSignTool
          path: publish/AzureSignTool.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: AzureSignTool ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: publish/AzureSignTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
